### ISSUE TITLE
Add printable view for members profile

### ISSUE THREAD

**Issue by jszanto** [Moridrin/ssv-frontend-members#63]
Add the option to print the information of a member along with a prefilled form to sign for direct debit

**Comment by JBerkvens** [comment]
I've started working on this today (we're going to create a PDF with FPDF and print that (this will be done in the WP-Admin section somewhere)).

**Comment by jszanto** [comment]
A small tip, use mPDF instead. It is much better maintained than FPDF and it allows you to easily convert html in to a pdf.

**Comment by JBerkvens** [comment]
We still worked with FPDF (because I already knew how to use that and had already written a couple of useful functions for it).
